name: Build and Upload Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Use the version that your script supports
          cache: 'pip'
          
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build using Nuitka
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: img_comp_grid_maker.py
          onefile: true
          enable-plugins: tk-inter
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
